# Variables
DIRECTION = src/
EXECUTABLE = main

all :
	cd $(DIRECTION) && $(MAKE)
	cp $(DIRECTION)$(EXECUTABLE) .

clean:
	rm -f src/*.o src/$(EXECUTABLE) $(EXECUTABLE) 

help:
	@echo "Targets:"
	@echo " all : Generate the AES binary file from the source files."
	@echo " clean : Remove all temporary files + binary file generated by the compilation."
	@echo " help : Display the targets of the Makefile with a short description."

.PHONY: all clean help